#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV

bspc config border_width         0
bspc config window_gap          20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Google-chrome desktop='^2'

# polybar
polybar -r &

# notification
/usr/bin/dunst &

# picom
picom -b &

# wallpaper 
~/.fehbg &

# xresources
xrdb ~/.Xresources &

# cursor
xsetroot -cursor_name left_ptr &
